### ISSUE TITLE
Divide by zero impacting Monthly Efficiency and Daily Efficiency

### ISSUE THREAD

**Issue by wralb** [dan-r/HomeAssistant-NissanConnect#12]
**What happened?**
Monthly Efficiency and Daily Efficiency may be marked 'Unavailable' and a division by zero error logged when the car has not been driven during the day.  This is generally notice when restarting Home Assistant before the vehicle has been used on the day.

**To Reproduce**

- Restart Home Assistant **before** the vehicle has been used on any particular day.  
- Note the Divide By Zero error raised because consumed_electricity is presumably zero
- Note that sensor.ariya_daily_efficiency (or similar) and sensor.ariya.monthly_efficiency are marked 'Unknown'.

**Expected behavior**

- The situation where consumed energy is zero is handled gracefully.  Perhaps either by setting to zero or to the previous periods final value.  
- This should be apply to daily data and monthly data (assuming the same issue could occur at the beginning of the month)

**Log Output**
```
Mar 02 16:49:08 hass hass[57717]:     self.async_update_listeners()
Mar 02 16:49:08 hass hass[57717]:   File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
Mar 02 16:49:08 hass hass[57717]:     update_callback()
Mar 02 16:49:08 hass hass[57717]:   File "/home/homeassistant/.homeassistant/custom_components/nissan_connect/sensor.py", line 235, in _handle_coordinator_update
Mar 02 16:49:08 hass hass[57717]:     self._state = self._lambda(summary[0])
Mar 02 16:49:08 hass hass[57717]:                   ^^^^^^^^^^^^^^^^^^^^^^^^
Mar 02 16:49:08 hass hass[57717]:   File "/home/homeassistant/.homeassistant/custom_components/nissan_connect/sensor.py", line 48, in <lambda>
Mar 02 16:49:08 hass hass[57717]:     StatisticSensor(coordinator_stats, data[vehicle], 'daily', lambda x: x.total_distance / x.consumed_electricity, 'daily_efficiency', 'mdi:ev-station', SensorDeviceClass.DISTANCE, UnitOfLength.KILOMETERS, 2, imperial_distance),
Mar 02 16:49:08 hass hass[57717]:                                                                          ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
Mar 02 16:49:08 hass hass[57717]: ZeroDivisionError: float division by zero
```

**Home Assistant Version**
2024.2.5 in python 3.12 venv on Ubuntu VM on Xen Orchestra

**Integration Version**
0.4.2

**Additional context**
Vehicle is Nissan Ariya

**Comment by dan-r** [comment]
Thanks for reporting this, I've changed that method to catch errors in the calculation and default to returning 0 in v0.4.3. 
Please let me know if you see this sort of thing again!

**Comment by wralb** [comment]
Thanks! Tested: issue is gone after installing v0.4.3.
