### ISSUE TITLE
Start to charge remotly

### ISSUE THREAD

**Issue by cyril164** [dan-r/HomeAssistant-NissanConnect#18]
Hello,
Is it possible to start the charging process remotely with this integration ?
I can see if the cable is connected and if the car is charging, but I didn't find a button to start the charge (like on the NissanConnect app) Is it plan to implement it ?

Thank you ;-)

Cyril

**Comment by dan-r** [comment]
I haven't added it yet because it isn't something I personally use (I've got a 'smart' charger), but will look into it as it should be fairly straightforward to add.

**Comment by dan-r** [comment]
@cyril164 I've added a 'Start Charge' button in v0.5.0-beta.1. Would you mind trying this out? ([HACS beta instructions](https://hacs.xyz/docs/faq/beta/)).
