### ISSUE TITLE
Ariya range missing, or doesn't update

### ISSUE THREAD

**Issue by celodnb** [dan-r/HomeAssistant-NissanConnect#25]
Firstly, just wanted to say thanks for making this an integration! I've been using the Node-Red hack method of getting the information into HA for months, so having this is much easier :-)

However, one thing i'm missing from the Node-Red method is the current range of the car (Nissan Ariya). I can see that there are two entities exposed by this integration (Range AC off and Range AC on), but they don't seem to update, just show as unknown. 

Are these two range entities available for the Ariya? If not, is it possible to expose the range?

**Comment by dan-r** [comment]
The Ariya seems to expose certain values (like these) on a different API endpoint to other cars (especially the Leaf). If you can provide the API endpoint that exposes this for the Ariya I can try to implement it?

**Comment by celodnb** [comment]
Hi Dan, is it possible you could point to a resource, or give me an idea as to how I can find the API endpoints you require? I'm more than happy to help, I just don't know where to look. Thanks 👍

**Comment by dan-r** [comment]
@celodnb apologies for not getting back sooner. If you're using the node-red flows, the URL that you are fetching from is the endpoint. Might be worth playing around with those flows and seeing what gives you the right info?

**Comment by Krolykke** [comment]
@celodnb, I made a sort of workaround for estimated range without taking AC in concideration. Try adding this in a markdown card somewhere, and change your battery size to fit:

`{## Imitate available variables: ##}
{% set Ariya_battery_capacity = {
  "capacity": 87,
  "unit": "KwH"
} %}

The cars total battery capacity is {{ Ariya_battery_capacity.capacity }} {{ Ariya_battery_capacity.unit }}.

SOC is at the moment {{ (states('sensor.ariya_battery_level')) }}% or about {{ Ariya_battery_capacity.capacity / 100 * (states('sensor.ariya_battery_level')) | int }} {{ Ariya_battery_capacity.unit }}

With your average km or miles/kwh ({{ (states('sensor.ariya_monthly_efficiency'))| round (2) }} km/kwh) your estimated range is {{ ((Ariya_battery_capacity.capacity / 100 * (states('sensor.ariya_battery_level')) | int) * (states('sensor.ariya_monthly_efficiency')) | round (2)) | round (2) }} km or miles.
`
