### ISSUE TITLE
Please add 2 more Spanish and Russian translations to your integration

### ISSUE THREAD

**Issue by SpainBoys** [dan-r/HomeAssistant-NissanConnect#26]
Please add 2 more Spanish and Russian translations to your integration:

[es.json](https://github.com/dan-r/HomeAssistant-NissanConnect/files/15387579/es.json)

[ru.json](https://github.com/dan-r/HomeAssistant-NissanConnect/files/15387581/ru.json)

**Comment by dan-r** [comment]
Thank you so much for this contribution! I'll release the new version with these shortly. Apologies for not getting to it sooner
