### ISSUE TITLE
Failed to set up: Access is denied for this resource

### ISSUE THREAD

**Issue by hammn** [dan-r/HomeAssistant-NissanConnect#30]
I have the latest stable version of HA and _previously_ this year (or maybe the end of the last?) I had a working installation of this NissanConnect component by uploading the individual files.

Later I experienced something was broken and - details are unclear - after a while I reinstalled the component. When reconfiguring, it gave me the error: "Access is denied for this resource"

**I believe the error came at about the same time as my personal phone needed an update of the NissanConnect Services app, but my personal Android is too old and no longer supported. A friend's iPhone runs the app however, where login and Car connection works.**

Either way, I shook my head and waited a couple of months, to see if it magically solved itself. But here I am now, experiencing the same issue. App login works and has been re-tested before this post.

HA component login validation works, so I am using the correct credentials. I verify this by noting that the component refuses to set up if I supply an incorrect password.

With a successful login, and the component gives me a success message, it goes on to setting up. In this phase, I am informed about an error "Failed to set up" and I am informed I should check the logs.

Starting debug logs, I get the following:

> 2024-06-16 08:42:31.861 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nissan_connect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-06-16 08:54:53.356 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 08:55:04.402 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 08:55:42.964 INFO (MainThread) [custom_components.nissan_connect] Logging in to service
> 2024-06-16 08:55:43.535 DEBUG (MainThread) [custom_components.nissan_connect] Finding vehicles
> 2024-06-16 08:55:44.531 DEBUG (SyncWorker_29) [custom_components.nissan_connect.kamereon] Active features: [<Feature.MY_CAR_FINDER: '12'>, <Feature.MIL_ON_NOTIFICATION: '15'>, <Feature.VEHICLE_HEALTH_REPORT: '18'>, <Feature.APP_DOOR_LOCKING: '27'>, <Feature.FLEET_ASSET_INFORMATION: '29'>, <Feature.PAY_AS_YOU_DRIVE: '34'>, <Feature.APP_BASED_NAVIGATION: '35'>, <Feature.DESTINATION_SEND_TO_CAR: '37'>, <Feature.GOOGLE_PLACES_SEARCH: '40'>, <Feature.PREMIUM_TRAFFIC: '43'>, <Feature.THEFT_BURGLAR_NOTIFICATION_APP: '87'>, <Feature.HORN_AND_LIGHTS: '97'>, <Feature.CURFEW_ALERT: '98'>, <Feature.NAVIGATION_MAP_UPDATES: '217'>, <Feature.LAST_MILE_NAVIGATION: '227'>, <Feature.GOOGLE_STREET_VIEW: '229'>, <Feature.GOOGLE_SATELITE_VIEW: '230'>, <Feature.DRIVING_JOURNEY_HISTORY: '235'>, <Feature.ONLINE_PARKING_INFO: '243'>, <Feature.ONLINE_RESTAURANT_INFO: '244'>, <Feature.ONLINE_SPEED_RESTRICTION_INFO: '245'>, <Feature.WEATHER_INFO: '246'>, <Feature.ZONE_ALERT: '281'>, <Feature.SPEEDING_ALERT: '282'>, <Feature.CHARGING_START: '299'>, <Feature.CLIMATE_ON_OFF_NOTIFICATION: '311'>, <Feature.PLUG_IN_REMINDER: '314'>, <Feature.CHARGING_STOP_NOTIFICATION: '317'>, <Feature.BATTERY_STATUS: '319'>, <Feature.BATTERY_HEATING_NOTIFICATION: '320'>, <Feature.VEHICLE_STATE_OF_CHARGE_PERCENT: '322'>, <Feature.DRIVING_ANALYSIS: '340'>, <Feature.CO2_GAS_SAVINGS: '341'>, <Feature.ELECTRICITY_FEE_CALCULATION: '342'>, <Feature.CHARGING_CONSUMPTION_HISTORY: '344'>, <Feature.CHARGING_SPOT_UPDATES: '354'>, <Feature.CLIMATE_ON_OFF: '366'>, <Feature.LOCK_STATUS_CHECK: '2021'>, <Feature.TEMPERATURE: '2042'>]
> 2024-06-16 08:55:45.062 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 08:57:38.721 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 09:00:09.518 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 10:54:01.129 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 10:55:14.541 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 10:55:22.140 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 10:55:24.478 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 10:55:58.614 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]
> 2024-06-16 10:56:03.748 INFO (MainThread) [custom_components.nissan_connect] Logging in to service
> 2024-06-16 10:56:04.327 DEBUG (MainThread) [custom_components.nissan_connect] Finding vehicles
> 2024-06-16 10:56:05.283 DEBUG (SyncWorker_41) [custom_components.nissan_connect.kamereon] Active features: [<Feature.MY_CAR_FINDER: '12'>, <Feature.MIL_ON_NOTIFICATION: '15'>, <Feature.VEHICLE_HEALTH_REPORT: '18'>, <Feature.APP_DOOR_LOCKING: '27'>, <Feature.FLEET_ASSET_INFORMATION: '29'>, <Feature.PAY_AS_YOU_DRIVE: '34'>, <Feature.APP_BASED_NAVIGATION: '35'>, <Feature.DESTINATION_SEND_TO_CAR: '37'>, <Feature.GOOGLE_PLACES_SEARCH: '40'>, <Feature.PREMIUM_TRAFFIC: '43'>, <Feature.THEFT_BURGLAR_NOTIFICATION_APP: '87'>, <Feature.HORN_AND_LIGHTS: '97'>, <Feature.CURFEW_ALERT: '98'>, <Feature.NAVIGATION_MAP_UPDATES: '217'>, <Feature.LAST_MILE_NAVIGATION: '227'>, <Feature.GOOGLE_STREET_VIEW: '229'>, <Feature.GOOGLE_SATELITE_VIEW: '230'>, <Feature.DRIVING_JOURNEY_HISTORY: '235'>, <Feature.ONLINE_PARKING_INFO: '243'>, <Feature.ONLINE_RESTAURANT_INFO: '244'>, <Feature.ONLINE_SPEED_RESTRICTION_INFO: '245'>, <Feature.WEATHER_INFO: '246'>, <Feature.ZONE_ALERT: '281'>, <Feature.SPEEDING_ALERT: '282'>, <Feature.CHARGING_START: '299'>, <Feature.CLIMATE_ON_OFF_NOTIFICATION: '311'>, <Feature.PLUG_IN_REMINDER: '314'>, <Feature.CHARGING_STOP_NOTIFICATION: '317'>, <Feature.BATTERY_STATUS: '319'>, <Feature.BATTERY_HEATING_NOTIFICATION: '320'>, <Feature.VEHICLE_STATE_OF_CHARGE_PERCENT: '322'>, <Feature.DRIVING_ANALYSIS: '340'>, <Feature.CO2_GAS_SAVINGS: '341'>, <Feature.ELECTRICITY_FEE_CALCULATION: '342'>, <Feature.CHARGING_CONSUMPTION_HISTORY: '344'>, <Feature.CHARGING_SPOT_UPDATES: '354'>, <Feature.CLIMATE_ON_OFF: '366'>, <Feature.LOCK_STATUS_CHECK: '2021'>, <Feature.TEMPERATURE: '2042'>]
> 2024-06-16 10:56:05.845 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/__init__.py", line 54, in async_setup_entry
>     await hass.async_add_executor_job(vehicle.refresh)
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/nissan_connect/kamereon.py", line 863, in refresh
>     self.fetch_all()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 866, in fetch_all
>     self.fetch_cockpit()
>   File "/config/custom_components/nissan_connect/kamereon.py", line 1327, in fetch_cockpit
>     raise ValueError(body['errors'])
> ValueError: [{'status': 'Forbidden', 'code': '403', 'title': 'security.access', 'detail': 'Access is denied for this resource'}]

**Home Assistant Version**
Home Assistant

Core 2024.6.3
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240610.1

**Integration Version**
Zip download today. Release was made 3 days ago at time of writing:
@[dan-r](https://github.com/dan-r) dan-r
[ v0.5.2](https://github.com/dan-r/HomeAssistant-NissanConnect/tree/v0.5.2)
https://github.com/dan-r/HomeAssistant-NissanConnect/commit/a09d16b6d955adf2c38d49d72ea7913f5f538ef7

**Comment by dan-r** [comment]
Everything seems to be working with my NissanConnect account. Have you changed your password lately? If so you'll need to change this on the integration.

I'd also recommend installing [HACS](https://hacs.xyz/) to keep your custom integrations up to date

**Comment by hammn** [comment]
> Everything seems to be working with my NissanConnect account. Have you changed your password lately? If so you'll need to change this on the integration.

Hello, thanks for the quick response.

I have reset my password through the app with NissanConnect Services, _removed and readded_ the entry in the integration configuration on /config/integrations/integration/nissan_connect

So I don't believe the issue is with the authentication credentials, as this is logged:

> 2024-06-16 08:55:42.964 INFO (MainThread) [custom_components.nissan_connect] Logging in to service
> 2024-06-16 08:55:43.535 DEBUG (MainThread) [custom_components.nissan_connect] Finding vehicles
> 2024-06-16 08:55:44.531 DEBUG (SyncWorker_29) [custom_components.nissan_connect.kamereon] Active features: [<Feature.MY_CAR_FINDER: '12'>, <Feature.MIL_ON_NOTIFICATION: '15'>, <Feature.VEHICLE_HEALTH_REPORT: '18'>, <Feature.APP_DOOR_LOCKING: '27'>, <Feature.FLEET_ASSET_INFORMATION: '29'>, <Feature.PAY_AS_YOU_DRIVE: '34'>, <Feature.APP_BASED_NAVIGATION: '35'>, <Feature.DESTINATION_SEND_TO_CAR: '37'>, <Feature.GOOGLE_PLACES_SEARCH: '40'>, <Feature.PREMIUM_TRAFFIC: '43'>, <Feature.THEFT_BURGLAR_NOTIFICATION_APP: '87'>, <Feature.HORN_AND_LIGHTS: '97'>, <Feature.CURFEW_ALERT: '98'>, <Feature.NAVIGATION_MAP_UPDATES: '217'>, <Feature.LAST_MILE_NAVIGATION: '227'>, <Feature.GOOGLE_STREET_VIEW: '229'>, <Feature.GOOGLE_SATELITE_VIEW: '230'>, <Feature.DRIVING_JOURNEY_HISTORY: '235'>, <Feature.ONLINE_PARKING_INFO: '243'>, <Feature.ONLINE_RESTAURANT_INFO: '244'>, <Feature.ONLINE_SPEED_RESTRICTION_INFO: '245'>, <Feature.WEATHER_INFO: '246'>, <Feature.ZONE_ALERT: '281'>, <Feature.SPEEDING_ALERT: '282'>, <Feature.CHARGING_START: '299'>, <Feature.CLIMATE_ON_OFF_NOTIFICATION: '311'>, <Feature.PLUG_IN_REMINDER: '314'>, <Feature.CHARGING_STOP_NOTIFICATION: '317'>, <Feature.BATTERY_STATUS: '319'>, <Feature.BATTERY_HEATING_NOTIFICATION: '320'>, <Feature.VEHICLE_STATE_OF_CHARGE_PERCENT: '322'>, <Feature.DRIVING_ANALYSIS: '340'>, <Feature.CO2_GAS_SAVINGS: '341'>, <Feature.ELECTRICITY_FEE_CALCULATION: '342'>, <Feature.CHARGING_CONSUMPTION_HISTORY: '344'>, <Feature.CHARGING_SPOT_UPDATES: '354'>, <Feature.CLIMATE_ON_OFF: '366'>, <Feature.LOCK_STATUS_CHECK: '2021'>, <Feature.TEMPERATURE: '2042'>]
> 2024-06-16 08:55:45.062 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NissanConnect Account for nissan_connect
> Traceback (most recent call last):
etc.

So it feels more like I make an unauthorized request _after_ a successful login.

**Comment by crdev** [comment]
FWIW, there is [this commit in dartnissanconnect](https://gitlab.com/tobiaswkjeldsen/dartnissanconnect/-/commit/e0301993e872a63c059c3afaa258b413d435fe0e). Could it be by chance related?

**Comment by dan-r** [comment]
That's been implemented under [this commit](https://github.com/dan-r/HomeAssistant-NissanConnect/commit/32044a1497dcf2849d2d3772f59510575449fb4e) so shouldn't be the problem. 

It seems weird because it's authenticated enough to get the list of features, but then seems to fail...

**Comment by hammn** [comment]
> That's been implemented under [this commit](https://github.com/dan-r/HomeAssistant-NissanConnect/commit/32044a1497dcf2849d2d3772f59510575449fb4e) so shouldn't be the problem.
> 
> It seems weird because it's authenticated enough to get the list of features, but then seems to fail...

I can confirm that this commit is also on my HA platform.

I will setup HACS to avoid second-guessing the file versions, then return here with the results. :)

**Comment by dan-r** [comment]
Did you have any luck with this?
