### ISSUE TITLE
Sunroof status

### ISSUE THREAD

**Issue by andershomeassistant** [dan-r/HomeAssistant-NissanConnect#34]
My wife did it.... Left the car overnight with the sunroof open and then it started raining....

If the state of the sunroof (open/closed) was read, that could be added to a helper (timer). My thought was to add a timer and if the sunroof was open for more that 60 minutes a messages is sent to mobile phone :-)

**Comment by dan-r** [comment]
Which car do you have? Not sure if that's something that can be read, but if it's state shows in the Nissan app then it's doable.

**Comment by andershomeassistant** [comment]
It's an Ariya.
Can't see the state in the app, but the Node-Red option can show both windows and sunroof

**Comment by dan-r** [comment]
Can you check if they are actually accurate? I believe my Leaf returns door states from one of the API endpoints but they always show as closed

**Comment by andershomeassistant** [comment]
I'm getting the status from doors, hatch and enginehood through Logstatus request (mqtt)
It seams like Nissan removed the sunroof in the latest update - at least it not preset anymore as it was dec 2023

Close the issue and if Nissan includes the sunroof state again i'll just re-open
Thx for the great work

https://community-assets.home-assistant.io/optimized/4X/3/0/c/30cf79ae15fb2b08050fcce20ce29fd0d4ba5498_2_930x750.png

**Comment by dan-r** [comment]
I get the same for my Leaf but none of them show any state other than closed. Let me know and reopen this if you manage to get that data out of yours accurately and it pops up again on that output. 

Dan
