### ISSUE TITLE
Not able to login to the integration- "Invalid credentials provided"

### ISSUE THREAD

**Issue by chriss10an** [dan-r/HomeAssistant-NissanConnect#36]
Trying to login to the integration when the following error-message occurs:

"Invalid credentials provided"

I am quit confident that my credentials are correct given that i´m allowed to login with the same input information on IOS and web interface.

**Comment by dan-r** [comment]
What country are you in?

Are there any errors in the log?

Are you entering the credentials manually or using a password manager? Password managers sometimes fill the wrong fields in home assistant config flows.

**Comment by chriss10an** [comment]
Hi dan-r, 

I'm located in Norway,

no other error's:

![image](https://github.com/user-attachments/assets/8fde19ab-ae5f-4c5d-b910-15264976bf7e)


credentials are entered manually withouy any form of password manager. 

any suggestions?

as mentioned, IOS app and web page/interface are working as it should.

**Comment by MrTango** [comment]
I have the same problem. But App and website are working.

**Comment by SpainBoys** [comment]
Read this post
https://github.com/dan-r/HomeAssistant-NissanConnect/issues/19

**Comment by chriss10an** [comment]
> Read this post #19

Hi, 

If i have understood your issue and your solution correctly: I havent typed in the incorrect password stored from a password manager application from my phone.  I am very confident that my password in entered correctly, since im manually typing in on my computer, and that i'm allowed to login on the Nissan connect webpage with the same credentials. 

thanks,

**Comment by SpainBoys** [comment]
> > Read this post #19
> 
> Hi,
> 
> If i have understood your issue and your solution correctly: I havent typed in the incorrect password stored from a password manager application from my phone. I am very confident that my password in entered correctly, since im manually typing in on my computer, and that i'm allowed to login on the Nissan connect webpage with the same credentials.
> 
> thanks,

Look in the password manager for this site and take your username and password from there.
![Screenshot_20240811_160439_Google Play services](https://github.com/user-attachments/assets/94c34d94-3292-436f-b719-def4b88d2a12)

**Comment by chriss10an** [comment]
> the password manager for this site and take your username and password fro

hi,

i have no password nor credentials stored or linked to that adress, my password when creating my Nissan account is rooted under "login.nissan.eu"

**Comment by dan-r** [comment]
Just to confirm, what app do you use to access your car? I use 'NissanConnect' and my credentials are for kamereon.org

**Comment by chriss10an** [comment]
> Just to confirm, what app do you use to access your car? I use 'NissanConnect' and my credentials are for kamereon.org

Hi Dan,

i use Nissan EV, i have an 2018 Nissan Tekna.

**Comment by MrTango** [comment]
I can login via nissan.de (You+Nissan) which does the login via login.nissan.eu....
But in HA with the integration the login does not work.
Username and password are correct.
With the Nissan connect EV the login works fine too.

**Comment by dan-r** [comment]
@chriss10an @MrTango this integration is only for cars that use the NissanConnect app. NissanConnect EV and other apps are not supported but there are other integrations out there that will work with your car.

I'll put a note on the README to make it more clear in future.

**Comment by MrTango** [comment]
@dan-r but the readme says EV focused. I have an Nissan NV200 and use the Nissan Connect EV app on android.
If you have a pointer to other projects, would be great.
It is a bit confusing with the different namings for Nissan connect app ;).

**Comment by dan-r** [comment]
I believe the "Nissan Leaf" integration built into home assistant will work for you. All new Nissan vehicles (from somewhere around 2018-2020 depending on region), ICE or EV all use "NissanConnect" now.

Here in the UK at least the NissanConnect EV app has been discontinued and no longer works for pre-2019 vehicles, with 2G network decommissioning being used as an excuse... even though 2G is being kept around here for the next 5 years at least for M2M applications just like these!
