### ISSUE TITLE
not a valid add-on repository

### ISSUE THREAD

**Issue by ettienem1001** [dan-r/HomeAssistant-NissanConnect#40]
Any idea why I would get the following error when trying to add to add-on repos?

https://github.com/dan-r/HomeAssistant-NissanConnect/ is not a valid add-on repository

When I try https://github.com/dan-r/HomeAssistant-NissanConnect/releases I get the following:
Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/dan-r/HomeAssistant-NissanConnect/releases /data/addons/git/59a68005 stderr: 'Cloning into '/data/addons/git/59a68005'... remote: Not Found fatal: repository 'https://github.com/dan-r/HomeAssistant-NissanConnect/releases/' not found '

**Comment by dan-r** [comment]
This is not an add-on repository and can only be added as a [HACS repository](https://hacs.xyz/docs/faq/custom_repositories/)
