### ISSUE TITLE
2022 ARIYA Evolve 87 kWh  almost working (sensor issues)

### ISSUE THREAD

**Issue by Krolykke** [dan-r/HomeAssistant-NissanConnect#44]
Installed like a charm.

Most works but following sensors is showing as "Unknown":

Charge Time (3kW)
Charge Time (6kW)
Last Updated
Range (AC Off)
Range (AC On)

**Comment by dan-r** [comment]
I think this is related to the closed #25. The Ariya has the same data but under different API endpoints. I've only got a Leaf so haven't been able to work any further on it

**Comment by Krolykke** [comment]
Can I help in any way?

**Comment by dan-r** [comment]
Looks like the dartnissanconnect library [now supports](https://github.com/Tobiaswk/dartnissanconnect/commit/e0c9c9d1f65dd98c2f3db3617e0b66a695e5bbfd) some more info for the Ariya. The API implementation of this integration is basically dartnissanconnect translated to Python so it should be relatively straightforward to get that support over. I'll start taking a look.

**Comment by dan-r** [comment]
Right, I've given it a go. Would you mind testing out v0.6.1-beta.1?

**Comment by Krolykke** [comment]
> Right, I've given it a go. Would you mind testing out v0.6.1-beta.1?

Sorry I missed this :-(
