### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by Krolykke** [dan-r/HomeAssistant-NissanConnect#45]
I would love to see a danish translation of this custom integration. I can help with that.

**Comment by dan-r** [comment]
For the translation, could you please take a look at the existing translations in [this folder](https://github.com/dan-r/HomeAssistant-NissanConnect/tree/main/custom_components/nissan_connect/translations) and then if you create a file in that folder called dk.json, copy in the contents of en.json and update the required fields, there should be an option to 'Propose changes'. 

You only need to update the strings in the JSON, the unique keys on the left (interval, interval_charging etc) need to remain in English - you can see what I mean by looking at some of the other translations.

**Comment by dan-r** [comment]
All in now, thanks again!
