### ISSUE TITLE
Add button entity to allow triggering a data poll

### ISSUE THREAD

**Issue by ptashek** [dan-r/HomeAssistant-NissanConnect#51]
**Is your feature request related to a problem? Please describe.**
I have an integration with my charger, which fully automates the charigng process as soon as the car is plugged-in.

Before I setup charge session parameters and unlock the charger, I want to make sure - with some degree of confidence - that it is my car that was plugged in, and that it is located withing the bounds of the home zone. This is very useful in scenarios where the charger is potentially accessible to the public (e.g.  open driveway). While I can update data from Nissan, I cannot force-wake the car to poll it, so this involves waiting for the next poll interval to retrieve latest charge state and location data.

I could lower the poll interval, but it can lead to rapid draining of the 12V battery and many issues that result from it. Learned the hard way! A permanent 10-minute poll interval drains the 12V battery flat in about 4 days.

**Describe the solution you'd like**
Adding a button entity that would allow triggering a data poll on demand would solve this issue. This also replicates similar functionality in the NissanConnect app.

**Comment by dan-r** [comment]
The update data button should allow you to do what you're asking. It polls the car and fetches the latest data.

**Comment by ptashek** [comment]
Oh, that's great. I wasn't aware that it forces a poll already. Thanks for the quick response, and your work in the integration!

**Comment by dan-r** [comment]
Its something I need to make a bit clearer in the documentation, so thank you for the reminder! :)

I have a very similar setup to what you described with my Leaf and Ohme charger.

Ohme says car plugged in -> Update Nissan and wait -> Update Nissan again -> Nissan says plugged in and is at home -> Approve
