### ISSUE TITLE
Climate not being reported

### ISSUE THREAD

**Issue by davelegg83** [dan-r/HomeAssistant-NissanConnect#55]
For quite  a while not the climate and internal temp of my leaf isn't being shown in the app. It simpy says 'This entity is no longer being provided by the nissan_connect integration. If the entity is no longer in use, delete it in settings.'

Is this because I cancelled the £1.99 subscription to control the climate of my leaf?
Running the lastest version of HA

**Comment by dan-r** [comment]
Sounds like you've hit the nail on the head. The integration will stop providing the entities if the API says your car doesn't have that 'capability', and it seems like the capability disappears if you don't have a subscription to cover it.

When my car turns 3 in March and I lose the free climate control I'll see if it's possible to work around any of it!
