### ISSUE TITLE
0 time at 3kW, but 1H at 6kW

### ISSUE THREAD

**Issue by reedy** [dan-r/HomeAssistant-NissanConnect#63]
![Screenshot 2024-10-24 at 01 12 08](https://github.com/user-attachments/assets/501623af-2f12-4a6c-b0d3-af4d4de576c2)

I'm guessing this is just weirdness from their API, but...

**Comment by dan-r** [comment]
Yeah these are just the times that come straight back from the Nissan API. You can also see them in the My Leaf app. There's some weirdness about how they display when charging. IIRC when charging, they all show as 0 except your current charge speed, so from this screenshot I'd think you were charging at 6kW
