### ISSUE TITLE
Daily...

### ISSUE THREAD

**Issue by reedy** [dan-r/HomeAssistant-NissanConnect#64]
![Screenshot 2024-10-24 at 01 12 05](https://github.com/user-attachments/assets/045d2946-41df-4dcc-a07d-254e22473ec2)

Is this the best label? I'm guessing (as I've not driven anywhere today), this is actually "distance driven today" etc.

Or it just not updating/showing correctly for me for some reason?

Monthly makes sense that it's an average...

![Screenshot 2024-10-24 at 01 13 51](https://github.com/user-attachments/assets/3f8dc9db-e57c-4570-9562-f7a193943e1e)

**Comment by dan-r** [comment]
The efficiency entities are in miles/KwH, but I believe I had to choose miles as the unit when I implemented it so the conversion to km works properly.

**Comment by dan-r** [comment]
Ah I confused this with your other issue. Yes, daily efficiency as in since midnight. I guess the wording could be better

**Comment by dan-r** [comment]
Closing for now but agree it could be worded better. Will have a think and see if I can come up with something better
