### ISSUE TITLE
Nissan Server API for EU Juke ?

### ISSUE THREAD

**Issue by gui017** [dan-r/HomeAssistant-NissanConnect#69]
Hello Dan,

1/FYI the integration works fine with 2021 Nissan Juke Petrol -EU
2/ What is the API on Nissan Server (EU) that the integration connects to ? (I would like to see what information is available for my car model and maybe request additonal entities.

Thanks for your work 👍

**Comment by dan-r** [comment]
Glad its working for you - I'll add it to the tested list.

The API library is [here](https://github.com/dan-r/HomeAssistant-NissanConnect/blob/main/custom_components/nissan_connect/kamereon.py) and its very heavily based on [dartnissanconnect](https://github.com/Tobiaswk/dartnissanconnect). There's no documentation on the API so looking through the code is about as much as I can recommend. There's some info in this [forum thread](https://community.home-assistant.io/t/integration-for-nissanconnect-services/507695/) too.
