### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by RaptorG** [dan-r/HomeAssistant-NissanConnect#7]
**What happened?**
Not Really a bug. The documentation  needs correction. 
Installation instructions under HACS says  "Search for and install the Ohme addon from HACS"
It should say "Search for and install the Nissan Connect addon from HACS"

**To Reproduce**
N/A
**Expected behavior**
N/A
**Log Output**
N/A
**Home Assistant Version**
N/A
**Integration Version**
N/A
**Additional context**
N/A

**Comment by dan-r** [comment]
Doh, good spot - bet you couldn't tell that README started off as a copy from the Ohme integration :)

I've updated it in the dev branch (and for v0.3.3-beta.3), and it'll get updated on main when I next merge.
