### ISSUE TITLE
Dutch translation not correct

### ISSUE THREAD

**Issue by scns** [dan-r/HomeAssistant-NissanConnect#72]
**What happened?**
<img width="235" alt="image" src="https://github.com/user-attachments/assets/ddb9e939-1264-4d60-9e7e-23361ee0e3b1">
<img width="229" alt="image" src="https://github.com/user-attachments/assets/b6477eb0-dce6-4990-a637-0c2ed7fad9a2">

Translation of the entity's in dutch is wrong

**To Reproduce**
just install in dutch HA

**Expected behavior**
"Dagaelijkse ritafstand" and "dagelijkste ritten" must swap
"Maadelijkse ritafstand" and "Maandelijkse ritten" must swap

**Log Output**
NA

**Home Assistant Version**
Latest

**Integration Version**
<img width="232" alt="image" src="https://github.com/user-attachments/assets/68797820-e671-4571-ae43-e6bd9d2142c7">

**Additional context**

I will make a Pull Request with the changes for this issue

**Comment by dan-r** [comment]
Resolved by #73. Will publish a new version with this fix later today.
