### ISSUE TITLE
2 cars under 2 different accounts

### ISSUE THREAD

**Issue by g7ukk** [dan-r/HomeAssistant-NissanConnect#76]
Love this add add on but have a question/issue.
We have a Leaf and Qashqai, both under different email accounts.
Added both cars/logins but every time HA is restarted I need to go to the integrations and press reload.then they both work.
Am I doing something wrong for when using two card and two accounts?

**Comment by g7ukk** [comment]
Hi
Thankyou so much for the reply (I’m new to HA but making good progress)
So, I am running

  *
Core2024.11.1
  *   Supervisor2024.11.2
  *   Operating System13.2
  *   Frontend20241106.2


Nissan connect 1.0.0

I have two accounts for 1 leaf and 1 for Qashqai both using different email accounts.
What I find is when I reboot HA only 1 car reports back.
Left it some time since reboot and only 1 car showing. If I then go and reload each integration entity it works until next reboot.
What is odd (see screen shot) the 2nd entity shows 2 devices (leaf and qsshqai) but only 1 car was only ever registered to the account it uses.

Please let me know any steps you would like me to carry out to troubleshoot.
When it works it’s great!!
[image0.jpeg]


Regards
Greg Firth

On 11 Nov 2024, at 16:04, Dan Raper ***@***.***> wrote:

﻿

Is your Home Assistant and this integration up to date? There have been some recent changes that may address it.

If yes to the above:
The Nissan API sometimes likes to not send a response. This usually doesn't cause any issues, and just puts a warning in the logs, but during integration initialisation, errors tend to just abort the process. Are you seeing this intermittently or fairly consistently?

**Comment by dan-r** [comment]
I'd recommend updating the NissanConnect integration to the latest version and then removing the config entries for both accounts and adding them back again.

Bear in mind the 1.0.0 that shows in the Home Assistant menu isn't accurate.

**Comment by g7ukk** [comment]
Thanks.
Actually the integration updated this evening evening but after a restart it was the same so I’ll remove and add back the accounts as suggested
Regards
Greg Firth

On 11 Nov 2024, at 19:33, Dan Raper ***@***.***> wrote:

﻿

I'd recommend updating the NissanConnect integration to the latest version and then removing the config entries for both accounts and adding them back again.

Bear in mind the 1.0.0 that shows in the Home Assistant menu isn't accurate.

**Comment by g7ukk** [comment]
Hi
So I’ve built a new HA setup, x86 with HAOS and the Nissan integration.
With two vehicles, as in two accounts using different email address logins for two vehicles , on reboot only one vehicle works and you have to go to the entity and restart the non working vehicle.
It works fine then until you restart.

Happy to do any testing if you need.
Regards
Greg Firth

On 11 Nov 2024, at 19:33, Dan Raper ***@***.***> wrote:

﻿

I'd recommend updating the NissanConnect integration to the latest version and then removing the config entries for both accounts and adding them back again.

Bear in mind the 1.0.0 that shows in the Home Assistant menu isn't accurate.

**Comment by g7ukk** [comment]
Absolutely. Will give it a go and let you know.

**Comment by g7ukk** [comment]
Hi Dan,
Just to let you know I removed v0.7.0, restarted, installed 0.7.1 beta, restarted.
Added 2 accounts, restarted.
Both initiated with no problem.
Restarted again and still both initiated no problem.

It looks like the issues has been resolved

Thank you.

________________________________

**Comment by dan-r** [comment]
Good to hear - got a couple more things I want to sort out for the next release, so just keep on beta for now and a proper release should be out in the next few days.
