### ISSUE TITLE
Climate UI

### ISSUE THREAD

**Issue by jklingberg** [dan-r/HomeAssistant-NissanConnect#78]
I don't understand the Climate UI, can someone explain how it's supposed to work?
<img width="299" alt="Screenshot 2024-11-20 at 22 40 40" src="https://github.com/user-attachments/assets/a1046fe8-68d1-4ca2-8fee-db5b6e18d92b">

**Comment by dan-r** [comment]
The NissanConnect integration provides two climate controls:
* Mode: Off or On (Heat/Cool)
* Target Temperature: this must be set before turning the mode On

The large temperature is the target which can be set with the + and - arrows or by dragging the dot on the wheel, the smaller temperature is the cars current internal temperature. Depending on theme and device, these may show slightly differently.

**Comment by klingberg-cbs** [comment]
Thank you but I don't understand how the two? buttons at the bottom are supposed to work?
Is it enough to press the button with the "power"-icon to start the heater?
Or what is the left-side button (the one with the sun) used for?

**Comment by dan-r** [comment]
On and Off. Left one is on, right is off
